name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@latest
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        build_configuration: production
        base_href: /ngeat/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/ngeat
